### PR TITLE
Suntoh/navigate-game

### LINKED ISSUE #12: [FE] Game Room
Player’s name and score are appeared on the game client.

### PR DESCRIPTION
**Pull request by Suntoh**
### **Homepage**
- enter roomId to Join
- set host of the lobby
- create room / join room separately

### **Lobby**
- Wait for all player to ready
- start game button push all player
- send random start player

### **Game Page**
- core game 
- display for both players
- set turn
- set firstplayer
- timer for switching team

## Note

- waiting for rainfall from mark

### CODE REVIEW

**Review by Imeany12 — COMMENTED** [review]
Please resolve the conflict krub

**Comment by Suntoh** [comment]
> Please resolve the conflict krub

I used temporary old file commenting your work because login is not working now.

**Review by Imeany12 — APPROVED** [review]
LGTM 🚀 💯

**Comment by Suntoh** [comment]
> LGTM 🚀 💯

The user type works!

**Pull request merged**
